-- Up Migration

-- IDs are generated by the application with UUIDv7 to preserve time locality
-- without exposing sequential database identifiers.
CREATE TABLE organizations (
  id uuid PRIMARY KEY,
  name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  updated_at timestamptz(3) NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id uuid PRIMARY KEY,
  identity_subject text NOT NULL CHECK (char_length(btrim(identity_subject)) BETWEEN 1 AND 255),
  email text NOT NULL CHECK (char_length(btrim(email)) BETWEEN 3 AND 320),
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  updated_at timestamptz(3) NOT NULL DEFAULT now(),
  CONSTRAINT users_identity_subject_key UNIQUE (identity_subject)
);

CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));

CREATE TABLE workspaces (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id) ON DELETE RESTRICT,
  name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
  slug text NOT NULL CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'),
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  updated_at timestamptz(3) NOT NULL DEFAULT now(),
  CONSTRAINT workspaces_organization_slug_key UNIQUE (organization_id, slug)
);

CREATE TABLE memberships (
  workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN ('owner', 'admin', 'editor', 'viewer')),
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  updated_at timestamptz(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

CREATE INDEX memberships_user_id_idx ON memberships (user_id);

-- Down Migration

DROP TABLE memberships;
DROP TABLE workspaces;
DROP INDEX users_email_lower_key;
DROP TABLE users;
DROP TABLE organizations;
